#!/bin/bash

echo "pacman assist script"

echo "type 'u' to update, 'i' to (re)install a package, or 'r' for removing a package"

# main prompt
read -p "What would you like to do? " choice "update" "delete" "list"

# update the system if the user chose `u`
if [[ $choice == "u" ]]; then
  echo "updating the system..."
  sudo pacman -Syu
fi

# remove a package if the user chose `r`
if [[ $choice == "r" ]]; then
  echo "what package would you like to remove?"
  read -p "enter package for removal: " package
  sudo pacman -Runs $package
fi

# (re)installs a package if the user chose `i`
if [[ $choice == "i" ]]; then
  echo "what package would you like to (re)install?"
  read -p "enter package for installation: " package
  sudo pacman -S $package
fi
